### ISSUE TITLE
debug question

### ISSUE THREAD

**Issue by jhxu003** [yangnianzu0515/MoleRec#3]
Hi! 
When I was debugging your code I found a question confused me for a long time. And the details are as follows.
The code is from MoleRec.py -> Class MoleRecModel -> forward.
The source code are
```
def forward(
        self, substruct_data, mol_data, patient_data,
        ddi_mask_H, tensor_ddi_adj, average_projection
    ):
        seq1, seq2 = [], []
        for adm in patient_data:
            Idx1 = torch.LongTensor([adm[0]]).to(self.device)
            Idx2 = torch.LongTensor([adm[1]]).to(self.device)
            repr1 = self.rnn_dropout(self.embeddings[0](Idx1))
            repr2 = self.rnn_dropout(self.embeddings[1](Idx2))
            seq1.append(torch.sum(repr1, keepdim=True, dim=1))
            seq2.append(torch.sum(repr2, keepdim=True, dim=1))
        seq1 = torch.cat(seq1, dim=1)     ## torch.Size([1, 10489, 64]) ???
        seq2 = torch.cat(seq2, dim=1)     ## torch.Size([1, 10489, 64]) ???
        output1, hidden1 = self.seq_encoders[0](seq1)
        output2, hidden2 = self.seq_encoders[1](seq2)
```
In my debugging results, I noticed that the shapes of seq1 and seq2 are [1, 10489, 64]. This implies that in the subsequent GRU module, there is only one time step as input. Consequently, the GRU module behaves somewhat like a linear layer. I'm wondering if this is by design or if I made a mistake during debugging.
Part of my debug code are as follows.
```
patient_data = data_train
seq1, seq2 = [], []
rnn_dropout = torch.nn.Dropout(p = 0.5)
embeddings = torch.nn.ModuleList([
    torch.nn.Embedding(voc_size[0] , 64),
    torch.nn.Embedding(voc_size[1], 64)]
)
for step, input_seq in enumerate(patient_data):
    for adm_index,adm in enumerate(input_seq):
        Idx1 = torch.LongTensor([adm[0]])
        Idx2 = torch.LongTensor([adm[1]])
        repr1 = rnn_dropout(embeddings[0](Idx1))
        repr2 = rnn_dropout(embeddings[1](Idx2))
        seq1.append(torch.sum(repr1, keepdim=True, dim=1))
        seq2.append(torch.sum(repr2, keepdim=True, dim=1))
seq1 = torch.cat(seq1, dim=1)
seq2 = torch.cat(seq2, dim=1)
seq1.shape
## torch.Size([1, 10489, 64])
```

**Comment by yangnianzu0515** [comment]
Hello,

In the `seq_encoders` section of our model definition, the `batch_first` parameter for `torch.nn.GRU` is set to `True`. This indicates that the first dimension given to the GRU is the batch size, as shown by the "1" in [1, 10489, 64]. This means that for each forward pass in the model, we're only feeding data for one patient, as can be seen in the [training](https://github.com/yangnianzu0515/MoleRec/blob/master/src/training.py) portion of the code. Each patient is represented as a sequence, with each element of the sequence corresponding to a time step. Therefore, the statement "there is only one time step as input for the subsequent GRU module" is inaccurate. The dimension corresponding to the value 10489 likely represents the number of visits for the patient. I'm not sure why this number is so large in your case; it might be due to issues in data processing. I might not be of much help with data processing concerns, as it has been a long time and my memory on the specifics is hazy. We mentioned in our readme that our data processing approach was based on the SafeDrug code from a particular commit.

We borrowed this part of the code from the [SafeDrug](https://github.com/ycq091044/SafeDrug/blob/main/src/models.py).

Worth noting, as mentioned earlier, we only have one patient at a time here, meaning a batch size of 1. Thus, there isn't really a concept of batch parallelism, which to a certain extent might affect the training speed. You can also try to modify this part to be parallelized.

**Comment by jhxu003** [comment]
Thank you very much for your reply! It's been incredibly helpful! 
I apologize for not noticing the `batch_first` parameter earlier, and now I have a clear understanding of how this model works. Regarding the value 10489, I believe it represents the total number of medical visits. Since each patient has more than 2 visits, this number seems reasonable. 
Once again, thank you for your assistance! I was puzzled by this question for quite some time.

**Comment by yangnianzu0515** [comment]
I'm glad my response was able to effectively address your concerns.

**Comment by He-Yichen** [comment]
@jhxu003 Hi, how did you get the data_train? Did you use the processing.py to generate thes .pkl file?  Why this number is so large in your case.
The paper claims that the authors filter out the patients with only one visit. But I found that there are still 908 records in the data that contain one visit.
![image](https://github.com/yangnianzu0515/MoleRec/assets/90712879/cf8956a8-966a-445c-a0b8-4147a735ccf9)
I was puzzled by this question for quite some time.

**Comment by yangnianzu0515** [comment]
Our data preprocessing, apart from the substructure component, is entirely based on the preprocessing methods used in SafeDrug. According to the original SafeDrug paper, it does indeed filter out patients with only one visit. I have just reviewed the preprocessing code in detail. The `process_visit_lg2` function is tasked with selecting patients who have only one visit, and the subsequent use of `med_pd.merge` is correct. The parameter `how='inner'` ensures that only those `SUBJECT_ID`s appearing in `med_pd_lg2` are retained, meaning we keep only patients with multiple visit records. I didn't find any issues with the code. However, based on the image you've shown, there seems to be a problem. Unfortunately, I don't have access to these data on my current server to assist you further. Perhaps you could consult with the authors of SafeDrug for more clarity?

Regarding the model design, I believe both SafeDrug and our MoleRec are intended to accept patients with only one visit as input. Having only one visit means there are no historical visits, which is somewhat similar to a cold start scenario in recommendations. Therefore, in our paper, we did not specifically mention the need to filter out patients with only one visit. Regarding your reference to `"The paper claims..."`, I assume you are referring to the original SafeDrug paper, not ours? I have just reviewed our original text and did not find any mention of this, but it's possible that I might have overlooked it. If it is indeed in our paper, I would appreciate your guidance in pointing it out.

The dataset statistics reported in our paper are directly derived from the output of the `statistics` function in `processing.py`. I just realized that SafeDrug mentioned filtering out patients with only one visit in their appendix, which I might have previously overlooked. Since I always believed that both SafeDrug and our MoleRec, in terms of model design, are supposed to accept patients with only one visit, I didn't pay much attention to the issue of filtering out patients with only one visit. Therefore, I didn't thoroughly check SafeDrug's preprocessing code and the final processed data.

However, whether to filter out patients with only one visit or not is entirely up to you. As long as the data used across all your methods is consistent, it should be fine.

**Comment by He-Yichen** [comment]
@yangnianzu0515 Thank you very much for your reply! I found that a recently accept [paper](https://arxiv.org/abs/2312.12100) at AAAI 2023 filtered out 908 patients with only one visit by `data= [x for x in data if len(x) >= 2] `.The data in AAAI's paper is what I need. What confuses me is that the patient's historical visit record doesn't seem to be very important in medication recommendation because for each patient's first visit, it is a cold start scenario,and for all 14995 visit records, there is no historical record for 6350 visits.

**Comment by yangnianzu0515** [comment]
@He-Yichen Yes, therefore, I think that perhaps the cold start is indeed a meaningful issue, and I also believe that this scenario is quite common in reality, making it worthwhile to explore the task of medication recommendation in this specific context.

I warmly welcome any discussion on this matter!
